tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "anyenv"
brew "python@3.9"
brew "ccat"
brew "colordiff"
brew "fontforge"
brew "fzf"
brew "git"
brew "go"
brew "httpd", restart_service: true
brew "hub"
brew "imagemagick@6", link: true
brew "mysql@5.6", restart_service: true
brew "nodenv"
brew "pyenv"
brew "redis"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "volt"
brew "yarn"
