version: '2'

services:
   db:
     image: mysql:5.7
     container_name: wordpress-db
     volumes:
       - db_data:/var/lib/mysql
     env_file: .env


   wordpress:
     image: wordpress:latest
     container_name: wordpress
     depends_on:
       - db
     ports:
       - "8001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
     env_file: .env
volumes:
    db_data:
