format = """
$directory\
$git_branch\
$git_status\
$hostname\
$time
$character
"""

right_format = "$ruby"

[os]
disabled = false

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold dimmed red"

[time]
disabled = false
format = "[$time]($style) "
style = "bold dimmed cyan"

[battery]
disabled = true

[memory_usage]
disabled = true

[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"
style = "white"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "purple"

[git_status]
style = "purple"

[git_metrics]
disabled = true

[ruby]
format = "[$symbol($version )]($style) "
style = "red"
